/**
 * Magnetic declination: the correction from magnetic north to true north.
 *
 * A phone's magnetometer points at the magnetic pole, which is not the pole the
 * sky rotates around. Around 20 degrees separates the two in parts of North
 * America and the South Atlantic. Skipping this correction does not blur the
 * overlay -- it puts a different constellation under the crosshair.
 *
 * The grid is generated by `python tools/build_declination.py` from IGRF-14.
 */

import { normalize180 } from './angles.js';

/** The generated `declination.json`. */
export interface DeclinationGridJson {
  model: string;
  epoch: number;
  latMin: number;
  latMax: number;
  latStep: number;
  latCount: number;
  lonMin: number;
  lonStep: number;
  lonCount: number;
  /** Declination at the model epoch, degrees east, row-major with latitude outer. */
  decl: number[];
  /** Change per year, degrees. */
  rate: number[];
  /** Total field strength, nanotesla, at the model epoch. Absent from older
   *  catalogue builds. */
  intensity?: number[];
}

export interface DeclinationGrid extends Omit<DeclinationGridJson, 'decl' | 'rate' | 'intensity'> {
  decl: Float32Array;
  rate: Float32Array;
  intensity: Float32Array;
}

export function parseDeclinationGrid(json: DeclinationGridJson): DeclinationGrid {
  return {
    ...json,
    decl: Float32Array.from(json.decl),
    rate: Float32Array.from(json.rate),
    intensity: json.intensity ? Float32Array.from(json.intensity) : new Float32Array(0),
  };
}

/** Decimal year, for interpolating the model forward from its epoch. */
export function decimalYear(when: Date): number {
  const year = when.getUTCFullYear();
  const start = Date.UTC(year, 0, 1);
  const end = Date.UTC(year + 1, 0, 1);
  return year + (when.getTime() - start) / (end - start);
}

export interface DeclinationResult {
  /** Degrees to ADD to a magnetic bearing to get a true one. */
  degrees: number;
  /**
   * False when the position is outside the grid -- above 85 degrees latitude,
   * where declination changes too fast to interpolate and a compass is
   * unusable anyway. `degrees` is 0 in that case, so the app degrades to an
   * uncorrected heading rather than a wrong one.
   */
  reliable: boolean;
}

/**
 * Declination at a position and time, bilinearly interpolated.
 *
 * Longitude wraps; latitude does not, so the caller gets told when it has
 * walked off the top of the grid.
 */
export function magneticDeclination(
  grid: DeclinationGrid,
  latitude: number,
  longitude: number,
  when: Date = new Date(),
): DeclinationResult {
  if (latitude < grid.latMin || latitude > grid.latMax) {
    return { degrees: 0, reliable: false };
  }

  // Fractional grid position.
  const latPosition = (latitude - grid.latMin) / grid.latStep;
  const lonNormalized = normalize180(longitude);
  const lonPosition = (lonNormalized - grid.lonMin) / grid.lonStep;

  const latIndex = Math.min(Math.floor(latPosition), grid.latCount - 1);
  const lonIndex = Math.floor(lonPosition);

  const latFraction = latPosition - latIndex;
  const lonFraction = lonPosition - lonIndex;

  const latNext = Math.min(latIndex + 1, grid.latCount - 1);
  // Longitude is periodic: the column after the last is the first.
  const lonWrapped = ((lonIndex % grid.lonCount) + grid.lonCount) % grid.lonCount;
  const lonNext = (lonWrapped + 1) % grid.lonCount;

  const at = (row: number, column: number, table: Float32Array): number =>
    table[row * grid.lonCount + column] as number;

  const interpolate = (table: Float32Array): number => {
    // Corners are angles, so blend along the short way round -- otherwise a
    // cell straddling the +180/-180 declination wrap averages to nonsense.
    const bottomLeft = at(latIndex, lonWrapped, table);
    const bottomRight = bottomLeft + normalize180(at(latIndex, lonNext, table) - bottomLeft);
    const topLeft = bottomLeft + normalize180(at(latNext, lonWrapped, table) - bottomLeft);
    const topRight = bottomLeft + normalize180(at(latNext, lonNext, table) - bottomLeft);

    const bottom = bottomLeft + (bottomRight - bottomLeft) * lonFraction;
    const top = topLeft + (topRight - topLeft) * lonFraction;
    return bottom + (top - bottom) * latFraction;
  };

  const base = interpolate(grid.decl);
  const perYear = interpolate(grid.rate);
  const years = decimalYear(when) - grid.epoch;

  return { degrees: normalize180(base + perYear * years), reliable: true };
}

export interface FieldIntensityResult {
  /** Total geomagnetic field strength, nanotesla. */
  nanotesla: number;
  reliable: boolean;
}

/**
 * Total geomagnetic field strength at a position, bilinearly interpolated --
 * what a magnetometer should read if nothing nearby is interfering with it.
 *
 * A plain (non-angular) interpolation: unlike declination, intensity has no
 * wraparound to worry about, so this does not need the short-way-round blend
 * {@link magneticDeclination} uses. No secular-variation term either -- field
 * strength drifts a percent or so a decade, not worth a second rate grid the
 * way declination's bearing needs one.
 */
export function magneticFieldIntensity(
  grid: DeclinationGrid,
  latitude: number,
  longitude: number,
): FieldIntensityResult {
  if (grid.intensity.length === 0 || latitude < grid.latMin || latitude > grid.latMax) {
    return { nanotesla: 0, reliable: false };
  }

  const latPosition = (latitude - grid.latMin) / grid.latStep;
  const lonNormalized = normalize180(longitude);
  const lonPosition = (lonNormalized - grid.lonMin) / grid.lonStep;

  const latIndex = Math.min(Math.floor(latPosition), grid.latCount - 1);
  const lonIndex = Math.floor(lonPosition);
  const latFraction = latPosition - latIndex;
  const lonFraction = lonPosition - lonIndex;
  const latNext = Math.min(latIndex + 1, grid.latCount - 1);
  const lonWrapped = ((lonIndex % grid.lonCount) + grid.lonCount) % grid.lonCount;
  const lonNext = (lonWrapped + 1) % grid.lonCount;

  const at = (row: number, column: number): number =>
    grid.intensity[row * grid.lonCount + column] as number;

  const bottom = at(latIndex, lonWrapped) + (at(latIndex, lonNext) - at(latIndex, lonWrapped)) * lonFraction;
  const top = at(latNext, lonWrapped) + (at(latNext, lonNext) - at(latNext, lonWrapped)) * lonFraction;

  return { nanotesla: bottom + (top - bottom) * latFraction, reliable: true };
}
